variables:
  - name: enableMetrics
    default: "false"

---
serverConfig:
  disable: traefik

helmValues:

  kvdi:
   vdi:
    spec:
      auth:
        allowAnonymous: true
      app:
        auditLog: true
      {{ if eq .Vars.enableMetrics "true" }}
      metrics:
        prometheus:
          create: true
        grafana:
          enabled: true
        serviceMonitor:
          create: true
          labels:
            release: kube-prometheus-stack
      {{ end }}
  
  kube-prometheus-stack:
    # JUST installs the operator
    defaultRules:
      create: false
    prometheus:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    nodeExporter:
      enabled: false
    kubelet:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeDns:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeApiServer:
      enabled: false
    coreDns:
      enabled: false
