---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami
spec:
  type: {{ if eq .Vars.traefikDisabled "false" }}ClusterIP{{ else }}LoadBalancer{{ end }}
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
      annotations:
    spec:
      containers:
        - name: whoami
          image: "traefik/whoami:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80

{{ if eq .Vars.traefikDisabled "false" }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: whoami
  namespace: default
spec:
  rules:
    - host: {{ .Vars.dnsName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami
              servicePort: 80
{{ end }}
